services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: MyCHATAPP
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mail_catcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  db_data: